version: '3.7'

services:
  Authentication:
    image: authentication
    build:
      context: ../ImageAuthentication
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app